
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafid
 */

public class frmMain extends javax.swing.JFrame {
    String nis;
        String nama;
        String tempat;
        String tanggal;
        String kelas;
        String email;
        String alamat;
        String JK="";
        String nol_jam="",nol_menit="",nol_detik="";
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LabelJam = new javax.swing.JLabel();
        LabelTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        txtNIS = new javax.swing.JTextField();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        txtKelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        Tanggalan = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Biodata Siswa SMK Telkom");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 410, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 70, 180, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafid\\Downloads\\Image\\ts.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 10, 80, 80);

        LabelJam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJam.setForeground(new java.awt.Color(255, 255, 255));
        LabelJam.setText("Jam");
        jPanel1.add(LabelJam);
        LabelJam.setBounds(680, 60, 150, 17);

        LabelTanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        LabelTanggal.setText("Tanggal");
        jPanel1.add(LabelTanggal);
        LabelTanggal.setBounds(680, 20, 150, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 100);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 460, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Isian Data Siswa");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 130, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NIS");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nama");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 230, 130, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kelas");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 340, 130, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Email");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 400, 130, 20);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 280, 10);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(10, 420, 220, 30);
        jPanel2.add(txtNIS);
        txtNIS.setBounds(10, 70, 150, 30);

        buttonGroup1.add(rdLaki);
        rdLaki.setText("Laki - Laki");
        jPanel2.add(rdLaki);
        rdLaki.setBounds(10, 310, 100, 23);

        buttonGroup1.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");
        rdPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPerempuanActionPerformed(evt);
            }
        });
        jPanel2.add(rdPerempuan);
        rdPerempuan.setBounds(120, 310, 110, 23);
        jPanel2.add(txtKelas);
        txtKelas.setBounds(10, 360, 220, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 480, 240, 76);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Jenis Kelamin");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 290, 130, 20);
        jPanel2.add(txtNama);
        txtNama.setBounds(10, 130, 220, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tempat Lahir");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 170, 130, 20);
        jPanel2.add(txtTempatLahir);
        txtTempatLahir.setBounds(10, 190, 220, 30);
        jPanel2.add(Tanggalan);
        Tanggalan.setBounds(10, 250, 220, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 280, 590);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel3.add(Save);
        Save.setBounds(10, 10, 90, 30);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel3.add(Delete);
        Delete.setBounds(110, 10, 90, 30);

        Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel3.add(Clear);
        Clear.setBounds(210, 10, 90, 30);

        Refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel3.add(Refresh);
        Refresh.setBounds(310, 10, 90, 30);

        Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel3.add(Print);
        Print.setBounds(510, 10, 90, 30);

        Edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel3.add(Edit);
        Edit.setBounds(410, 10, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(300, 110, 610, 50);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "TempatLahir", "TanggalLahir", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 580, 510);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 170, 620, 530);

        setSize(new java.awt.Dimension(925, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rdPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPerempuanActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggalan.getDate());
        String JK = "";
        if(rdLaki.isSelected()){
                    JK = "L";
        }
        if (rdPerempuan.isSelected()) {
            JK = "P";
        }

        if("".equals(txtNIS.getText())||"".equals(txtNama.getText())||"".equals(txtKelas.getText())||"".equals(txtEmail.getText())||"".equals(txtAlamat.getText())||JK.equals("")||"".equals(txtTempatLahir.getText())||tanggal.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", 
            JOptionPane.WARNING_MESSAGE);
        }else{
            
                
        
        String SQL = "insert into  t_siswa (NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat) "
                + "VALUES('"+txtNIS.getText()+"', '"+txtNama.getText()+"', '"+txtTempatLahir.getText()+"', '"+tanggal+"', '"+JK+"',"
                + "'"+txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String NIS = tblData.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtNIS.setText("");
        txtKelas.setText("");
        buttonGroup1.clearSelection();
        txtEmail.setText("");
        txtAlamat.setText("");
        txtTempatLahir.setText("");
        Tanggalan.setDate(null);
        
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_RefreshActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        alamat = txtAlamat.getText();
        email = txtEmail.getText();
        nis = txtNIS.getText();
        nama = txtNama.getText();
        kelas = txtKelas.getText();
        tempat = txtTempatLahir.getText();
        String JK = "";
        //Attur Tanggal
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        tanggal = df.format(Tanggalan.getDate());
        //Atur Jenis Kelamin
        if (rdLaki.isSelected()) {
            JK = "L";
        }
        if ((rdPerempuan.isSelected())) {
            JK = "P";
        }
// TODO add your handling code here:
        if ("".equals(nis)||"".equals(nama)||"".equals(kelas)||"".equals(alamat)||"".equals(email)||JK.equals("")||tempat.equals("")||tanggal.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapidata", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "UPDATE t_siswa SET NIS='"+nis+"',"
                    + "NamaSiswa='"+nama+"',"
                    + "JenisKelamin='"+JK+"',"
                    + "Kelas='"+kelas+"',"
                    + "TempatLahir='"+tempat+"',"
                    + "TanggalLahir='"+tanggal+"',"
                    + "Email='"+email+"',"
                    + "Alamat='"+alamat+"'"
                    + "WHERE NIS='"+nis+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_EditActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris != -1){
        txtNIS.setText(tblData.getValueAt(baris, 0).toString());
        txtNama.setText((String) tblData.getValueAt(baris, 1));
        txtTempatLahir.setText((String) tblData.getValueAt(baris, 2));
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        Date dateFormat = null;
        try {
            dateFormat = date.parse(tblData.getValueAt(baris, 3).toString());
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        Tanggalan.setDate(dateFormat);
        String jk = tblData.getValueAt(baris, 4).toString();
        if(jk.equals("Laki - Laki"))
            rdLaki.setSelected(true);
        else 
            rdPerempuan.setSelected(true);
        
        txtKelas.setText(tblData.getValueAt(baris, 5).toString());
        txtEmail.setText(tblData.getValueAt(baris, 6).toString());
        txtAlamat.setText(tblData.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyy");
        LabelTanggal.setText(kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                LabelJam.setText("Jam "+jam + ":" + menit + ":" + detik );
            }
        };
        new Timer(100, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel LabelJam;
    private javax.swing.JLabel LabelTanggal;
    private javax.swing.JButton Print;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private com.toedter.calendar.JDateChooser Tanggalan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"NIS","NamaSiswa","TempatLahit","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM t_siswa";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String NIS = rs.getString(1);
               String NamaSiswa = rs.getString(2);
               String TempatLahir = rs.getString(3);
               String TanggalLahir = rs.getString(4);
               String JenisKelamin = "";
               if("L".equals(rs.getString(5))){
                   JenisKelamin = "Laki-Laki";
               }else{
                   JenisKelamin = "Perempuan";
               }
               String Kelas = rs.getString(6);
               String Email = rs.getString(7);
               String Alamat = rs.getString(8);
               String data [] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
               dtm.addRow(data);
           }   
        }catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
       tblData.setModel(dtm);
    }
}
